.\" Man page for gde2weather.
.TH "GDE2WEATHER" "1" "10 februar 2002" "" ""
.SH NAME
gde2weather \- Weather Applet for the GDE2 panel.
.SH SYNOPSIS

\fBgde2weather\fR [ \fB--activate-goad-server \fI[=GOAD_ID]\fB\fR ]

.SH "DESCRIPTION"
.PP
\fBgde2weather\fR displays the current temperature
and weather conditions in numeric and iconified form inside the
applet.
.PP
To add this applet to a Panel, right-click on the Panel and
choose Applets->Utility->GDE2 Weather
.SH "OPTIONS"
.TP
\fB--activate-goad-server\fR
(Internal use only) GOAD server ID to activate.

GOAD_ID is usually the applet name [\fBgde2weather\fR]
.SH "AUTHOR"
.PP
This manual page was written by Christian Marillat <marillat@debian.org> for
the Debian GNU/Linux system (but may be used by others).
