#!/usr/bin/env python

import sys, gde2_invest.chart

import gi
gi.require_version("Gtk", gde2_invest.defs.GTK_API_VERSION)
from gi.repository import Gtk

# Prepare i18n
import gettext, locale
gettext.bindtextdomain(gde2_invest.defs.GETTEXT_PACKAGE, gde2_invest.defs.GDE2LOCALEDIR)
gettext.textdomain(gde2_invest.defs.GETTEXT_PACKAGE)
locale.bindtextdomain(gde2_invest.defs.GETTEXT_PACKAGE, gde2_invest.defs.GDE2LOCALEDIR)
locale.textdomain(gde2_invest.defs.GETTEXT_PACKAGE)

if __name__ == "__main__":
	win = gde2_invest.chart.show_chart(sys.argv[1:])
	win.connect("destroy", lambda x: Gtk.main_quit())
	Gtk.main()
